### ISSUE TITLE
Screen rotation for Raspberrypi OS lite 

### ISSUE THREAD

**Issue by psychendPerspective** [laamaa/m8c#111]
Hi everyone and @laamaa 
I'm trying to get the m8c working correctly on the Raspberry OS lite 64-bit version or any other non-desktop OS environment. However, the GUI is in portrait mode and I'm not able to figure out how to use it in landscape mode.
Could anyone suggest a solution?
Here is my setup:
RPI 3b+
Full KMS driver
RPI OS lite 64 bit 

With the desktop environment, I'm facing issues where the application hangs and crashes after some time, even while using the software rendering option. Any help would be appreciated!

**Comment by psychendPerspective** [comment]
Thanks for the reply. Sorry, I meant the application hangs and doesn't respond to any inputs, it doesn't quit on the desktop environment. Could you let me know which OS and setup would be stable for running the application in landscape mode?

**Comment by laamaa** [comment]
Unfortunately I can't really give much recommendations other than to use a good power supply (preferably the official)  and a good quality USB cable to connect the device. All RPis should have enough power to run the program, depending on the system configuration and connected peripherals. The power supply and USB cable are important factors, the hanging might happen if the USB device cuts off due to power issues or something else.
