### ISSUE TITLE
[Improvement] Mention that there are also Prebuild Binaries for Linux in the README.md, and that `libserialport` is needed to use them

### ISSUE THREAD

**Issue by erNail** [laamaa/m8c#116]
The `README.md` states, that there are "[...] prebuilt binaries available [...] for Windows and recent versions of MacOS). Since the [releases](https://github.com/laamaa/m8c/releases) also show a linux binary, it should be mentioned in the README.md

I will create a Pull Request for this.

**Comment by laamaa** [comment]
Hi ! Thanks for the issue / PR. I'm not exactly sure about the usefulness of the current prebuilt Linux binary, so I probably don't want it even mentioned in the readme at this stage. (It's amd64 and requires the external libraries like you noted in the PR).

Making an AppImage or something like that would probably be better so that users wouldn't need to mess with the external libraries...

**Comment by erNail** [comment]
Hi, thanks for the feedback. I'll have a look at the options to avoid messing around with the external libraries. I'll give an update here or in another PR/Issue
