### ISSUE TITLE
Possible to specify resolution / dpi ?

### ISSUE THREAD

**Issue by markpendlebury** [laamaa/m8c#155]
Apologies this isn't really an issue more a question. I've looked through the docs/config and i don't see anything that suggests that this is possible.

Basically wondering if it's possible to specify the resolution of m8c? I'm running on steamdeck and honestly it runs perfectly but i do feel maybe the text / rendering is a little on the large side? So wondering if it's possible via the config file or some other way to specify a resolution?

Thanks

**Comment by laamaa** [comment]
Hi,

Unfortunately there's no separate option for that and I'm not sure there's an easy way to do it since SDL2 handles all the rendering stuff.

Normally the program tries to create a window that's the M8 resolution (320x240 or 480x320) but doubled, and if the window is scaled it tries to keep the aspect ratio correct. Unfortunately I don't own a Steam Deck so I don't know how it works there...

**Comment by markpendlebury** [comment]
Hi, 

Sorry for the slow reply, Github didn't notify me of your reply for some reason. 

I think I'm following what you're talking about. I've tried adjusting line 33 and 34 on [renderer.c](https://github.com/laamaa/m8c/blob/main/src/render.c) and forcing [fullscreen](https://github.com/laamaa/m8c/blob/1c4f2b9c32fd8a79b47fb8f93c2ee79d811025ff/src/render.c#L39) but it seems i am in fact seeing what you're explaining. The window its self fits to the specified resolution and initially startes without the boarder / window frames etc but the actual DPI remains the same.

I'll take a look at SDL2 and see if it's possible to implement on that side of things

Keep up the good work!
Thanks
