### ISSUE TITLE
FR: Supporting non button sdl keys?

### ISSUE THREAD

**Issue by peterswimm** [laamaa/m8c#25]
I have an 8bitdo controller, with the following mappings

Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b8,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Mac OS X,"

How do I map the h0.8 etc ones? It doesn't seem to support them in the ini. If I map the directions to a regular button it seems to work as intended.

**Comment by laamaa** [comment]
Doesn't work currently, the code in input.c checks only for SDL_JOYBUTTONDOWN and JOYBUTTONUP events. It shouldn't be too hard to add axis support as well though, especially since now things work with the ini file

**Comment by peterswimm** [comment]
Ah that would be great, it seems all my controllers do the axis method for their dpads! Ill change this to a feature request.

**Comment by laamaa** [comment]
I tried to hack some kind of support for analog axis (#27), wasn't as simple as I first thought but it works now at least with my Xbox One Gamepad. Could you please try pulling the most recent code and try if it works for you?

**Comment by peterswimm** [comment]
It works for me on the Xbox one controller but not the 8bitdo above.  Tagging @JeffAlyanak

**Comment by laamaa** [comment]
I rewrote most of the gamepad stuff since analog stuff was hard to add on top of the previous SDL events-based system. Analog axis events didn't seem work that reliably at least on my system. Now all buttons and axis are checked on every cycle in a simple system.

I also added the possibility to map all buttons to analog axis (so that xbone triggers etc. work for start/sel and so on), the mappings are in config.ini.

Could you please try pulling the latest source and check if all pads work normally now? I tested briefly with a knockoff USB PS3 pad and XBOne pad and both seemed to be fine now, with digital and analog.

**Comment by laamaa** [comment]
I think this works ok, I'll close the issue for now
