### ISSUE TITLE
Idea/Help - text/console only mode

### ISSUE THREAD

**Issue by jhohiii** [laamaa/m8c#47]
I am using m8c with great success.  Thank you!

I have installed it on a norns and it functions with a forwarded X display, however it is very laggy and the keyboard controls are often doubled.  I'm not asking for a fix.

I wondered if a Text mode could be done - possibly with ncurses.  I can try myself, but I can't figure out how to interpret the display stream to convert over to a text display.  I may be completely mistaken in taking this approach, but I wondered if you thought it may be possible and point me in the right direction.

**Comment by laamaa** [comment]
Hi jhohiii,

not easily, since the M8 sends simple drawing commands for the UI elements and the client pretty much just draws what it's told.

In theory this might be possible by translating text character x/y pixel coordinates to console rows/columns and using some custom code to draw the other elements, but it would probably make more sense to create a completely different application for this purpose than tweak m8c. It probably wouldn't even need SDL.
